import type { Question, QuestionFlow } from "@/features/qualification/types";

const founderQuestions: Question[] = [
  // --- EVERYONE (8 questions) ---
  {
    id: "full_name",
    question: "What is your full name?",
    type: "text",
    stage: "personal",
    required: true,
    validation: { minLength: 2 },
  },
  {
    id: "email",
    question: "What is your email address?",
    type: "email",
    stage: "personal",
    required: true,
  },
  {
    id: "linkedin",
    question: "What is your LinkedIn profile URL?",
    type: "url",
    stage: "personal",
    required: true,
    validation: { pattern: "linkedin.com" },
  },
  {
    id: "startup_name",
    question: "What is your startup called?",
    type: "text",
    stage: "startup",
    required: true,
  },
  {
    id: "industry",
    question: "Which industry are you in?",
    type: "select",
    stage: "startup",
    required: true,
    options: [
      { value: "fintech", label: "Fintech" },
      { value: "health", label: "Health / Bio" },
      { value: "saas", label: "SaaS" },
      { value: "ai-ml", label: "AI / ML" },
      { value: "climate", label: "Climate / Energy" },
      { value: "edtech", label: "Edtech" },
      { value: "ecommerce", label: "E-commerce" },
      { value: "other", label: "Other" },
    ],
  },
  {
    id: "problem_statement",
    question: "What problem are you solving?",
    type: "textarea",
    stage: "startup",
    required: true,
    validation: { minLength: 50 },
  },
  {
    id: "target_customer",
    question: "Who is your target customer?",
    type: "text",
    stage: "startup",
    required: true,
  },
  {
    id: "mvp_status",
    question: "What is your current stage?",
    type: "select",
    stage: "product",
    required: true,
    options: [
      { value: "idea", label: "Idea" },
      { value: "prototype", label: "Prototype" },
      { value: "mvp", label: "MVP" },
      { value: "revenue", label: "Revenue" },
    ],
  },
  // --- IDEA (4 questions) ---
  {
    id: "idea_why_now",
    question: "Why is now the right time for this startup?",
    type: "textarea",
    stage: "product",
    required: false,
  },
  {
    id: "idea_insight",
    question: "What insight do you have that others may be missing?",
    type: "textarea",
    stage: "product",
    required: false,
  },
  {
    id: "idea_biggest_assumption",
    question: "What is your biggest assumption?",
    type: "textarea",
    stage: "product",
    required: false,
  },
  {
    id: "idea_why_right_person",
    question: "Why are you the right person to solve this?",
    type: "textarea",
    stage: "product",
    required: false,
  },
  // --- PROTOTYPE (4 questions) ---
  {
    id: "prototype_what_built",
    question: "What have you built so far?",
    type: "textarea",
    stage: "product",
    required: false,
  },
  {
    id: "prototype_who_tested",
    question: "Who has tested it?",
    type: "textarea",
    stage: "product",
    required: false,
  },
  {
    id: "prototype_surprising_feedback",
    question: "What feedback surprised you?",
    type: "textarea",
    stage: "product",
    required: false,
  },
  {
    id: "prototype_next_milestone",
    question: "What is your next milestone?",
    type: "textarea",
    stage: "product",
    required: false,
  },
  // --- MVP (4 questions) ---
  {
    id: "mvp_active_users",
    question: "How many active users do you have?",
    type: "number",
    stage: "traction",
    required: false,
    validation: { min: 0 },
  },
  {
    id: "mvp_weekly_metric",
    question: "What metric are you tracking weekly?",
    type: "text",
    stage: "traction",
    required: false,
  },
  {
    id: "mvp_why_return",
    question: "Why do your users return?",
    type: "textarea",
    stage: "traction",
    required: false,
  },
  {
    id: "mvp_biggest_blocker",
    question: "What is your biggest blocker to growth?",
    type: "textarea",
    stage: "traction",
    required: false,
  },
  // --- REVENUE (5 questions) ---
  {
    id: "monthly_revenue",
    question: "What is your monthly revenue (USD)?",
    type: "number",
    stage: "traction",
    required: false,
    validation: { min: 0 },
  },
  {
    id: "growth_rate",
    question: "What is your month-over-month growth rate (%)?",
    type: "number",
    stage: "traction",
    required: false,
    validation: { min: 0, max: 100 },
  },
  {
    id: "revenue_acquisition_channel",
    question: "What is your best acquisition channel?",
    type: "text",
    stage: "traction",
    required: false,
  },
  {
    id: "revenue_biggest_bottleneck",
    question: "What is your biggest bottleneck today?",
    type: "textarea",
    stage: "traction",
    required: false,
  },
  {
    id: "revenue_post_raise_plan",
    question: "What is your post-raise plan?",
    type: "textarea",
    stage: "fundraising",
    required: false,
  },
  // --- EVERYONE (1 question) ---
  {
    id: "pitch_deck",
    question: "Upload your pitch deck (Optional)",
    type: "file",
    stage: "fundraising",
    required: false,
    helperText: "PDF only, max 10MB.",
  },
];

export const founderFlow: QuestionFlow = {
  type: "founder",
  title: "Founder Qualification",
  description:
    "Tell us about your startup journey. This helps us match you with the right investors.",
  questions: founderQuestions,
  totalQuestions: founderQuestions.length,
  stages: ["personal", "startup", "product", "traction", "fundraising"],
};
