import type { Question, QuestionFlow } from "@/features/qualification/types";

const founderQuestions: Question[] = [
  {
    id: "full_name",
    question: "What is your full name?",
    type: "text",
    stage: "personal",
    required: true,
    validation: { minLength: 2 },
  },
  {
    id: "email",
    question: "What is your email address?",
    type: "email",
    stage: "personal",
    required: true,
  },
  {
    id: "phone",
    question: "What is your phone number?",
    type: "tel",
    stage: "personal",
    required: true,
  },
  {
    id: "linkedin",
    question: "What is your LinkedIn profile URL?",
    type: "url",
    stage: "personal",
    required: true,
    validation: { pattern: "linkedin.com" },
  },
  {
    id: "prev_startup",
    question: "Have you started a company before?",
    type: "select",
    stage: "background",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
  {
    id: "industry_experience",
    question: "How many years of industry experience do you have?",
    type: "number",
    stage: "background",
    required: true,
    validation: { min: 0, max: 50 },
  },
  {
    id: "commitment",
    question: "Are you working on this full-time or part-time?",
    type: "select",
    stage: "background",
    required: true,
    options: [
      { value: "full-time", label: "Full-time" },
      { value: "part-time", label: "Part-time" },
    ],
  },
  {
    id: "startup_name",
    question: "What is your startup called?",
    type: "text",
    stage: "startup",
    required: true,
  },
  {
    id: "industry",
    question: "Which industries are you in?",
    type: "multiselect",
    stage: "startup",
    required: true,
    options: [
      { value: "fintech", label: "Fintech" },
      { value: "health", label: "Health / Bio" },
      { value: "saas", label: "SaaS" },
      { value: "ai-ml", label: "AI / ML" },
      { value: "climate", label: "Climate / Energy" },
      { value: "edtech", label: "Edtech" },
      { value: "ecommerce", label: "E-commerce" },
      { value: "consumer", label: "Consumer" },
      { value: "web3", label: "Web3 / Crypto" },
      { value: "hardtech", label: "Hardtech / Robotics" },
      { value: "space", label: "Space / Defense" },
      { value: "other", label: "Other" },
    ],
  },
  {
    id: "problem_statement",
    question: "What problem are you solving?",
    type: "textarea",
    stage: "startup",
    required: true,
    validation: { minLength: 50 },
  },
  {
    id: "target_customer",
    question: "Who is your target customer?",
    type: "text",
    stage: "startup",
    required: true,
  },
  {
    id: "mvp_status",
    question: "What is your current MVP status?",
    type: "select",
    stage: "product",
    required: true,
    options: [
      { value: "idea", label: "Idea" },
      { value: "prototype", label: "Prototype" },
      { value: "mvp", label: "MVP" },
      { value: "launched", label: "Launched" },
      { value: "revenue", label: "Revenue" },
    ],
  },
  {
    id: "active_users",
    question: "How many active users or customers do you have?",
    type: "number",
    stage: "traction",
    required: true,
    validation: { min: 0 },
  },
  {
    id: "monthly_revenue",
    question: "What is your monthly revenue (USD)?",
    type: "number",
    stage: "traction",
    required: true,
    validation: { min: 0 },
  },
  {
    id: "growth_rate",
    question: "What is your month-over-month growth rate (%)?",
    type: "number",
    stage: "traction",
    required: true,
    validation: { min: 0, max: 100 },
  },
  {
    id: "team_size",
    question: "How many people are on your team?",
    type: "number",
    stage: "team",
    required: true,
    validation: { min: 1 },
  },
  {
    id: "has_cofounder",
    question: "Do you have a co-founder?",
    type: "select",
    stage: "team",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
  {
    id: "funding_ask",
    question: "How much funding are you raising (USD)?",
    type: "number",
    stage: "fundraising",
    required: true,
    validation: { min: 0 },
  },
  {
    id: "pitch_deck",
    question: "Upload your pitch deck",
    type: "file",
    stage: "fundraising",
    required: true,
    helperText: "PDF only, max 10MB. Drag & drop or click to browse.",
  },
];

export const founderFlow: QuestionFlow = {
  type: "founder",
  title: "Founder Qualification",
  description:
    "Tell us about your startup journey. This helps us match you with the right investors.",
  questions: founderQuestions,
  totalQuestions: founderQuestions.length,
  stages: ["personal", "background", "startup", "product", "traction", "team", "fundraising"],
};

