import type { Question, QuestionFlow } from "@/features/qualification/types";

const investorQuestions: Question[] = [
  {
    id: "full_name",
    question: "What is your full name?",
    type: "text",
    stage: "personal",
    required: true,
    validation: { minLength: 2 },
  },
  {
    id: "email",
    question: "What is your email address?",
    type: "email",
    stage: "personal",
    required: true,
  },
  {
    id: "phone",
    question: "What is your phone number?",
    type: "tel",
    stage: "personal",
    required: true,
  },
  {
    id: "linkedin",
    question: "What is your LinkedIn profile URL?",
    type: "url",
    stage: "personal",
    required: true,
    validation: { pattern: "linkedin.com" },
  },
  {
    id: "investor_type",
    question: "What type of investor are you?",
    type: "select",
    stage: "profile",
    required: true,
    options: [
      { value: "angel", label: "Angel Investor" },
      { value: "vc", label: "Venture Capital" },
      { value: "family-office", label: "Family Office" },
      { value: "corporate", label: "Corporate VC" },
    ],
  },
  {
    id: "preferred_stage",
    question: "What stage do you typically invest in?",
    type: "select",
    stage: "profile",
    required: true,
    options: [
      { value: "pre-seed", label: "Pre-seed" },
      { value: "seed", label: "Seed" },
      { value: "series-a", label: "Series A" },
      { value: "series-b-plus", label: "Series B+" },
    ],
  },
  {
    id: "sector_focus",
    question: "Which sectors are you focused on?",
    type: "multiselect",
    stage: "profile",
    required: true,
    options: [
      { value: "fintech", label: "Fintech" },
      { value: "health", label: "Health / Bio" },
      { value: "saas", label: "SaaS" },
      { value: "ai-ml", label: "AI / ML" },
      { value: "climate", label: "Climate / Energy" },
      { value: "edtech", label: "Edtech" },
      { value: "ecommerce", label: "E-commerce" },
      { value: "other", label: "Other" },
    ],
  },
  {
    id: "cheque_min",
    question: "What is your minimum cheque size (USD)?",
    type: "number",
    stage: "profile",
    required: true,
    validation: { min: 0 },
  },
  {
    id: "cheque_max",
    question: "What is your maximum cheque size (USD)?",
    type: "number",
    stage: "profile",
    required: true,
    validation: { min: 0 },
  },
  {
    id: "deployment_timeline",
    question: "What is your typical deployment timeline?",
    type: "select",
    stage: "strategy",
    required: true,
    options: [
      { value: "0-3", label: "0–3 months" },
      { value: "3-6", label: "3–6 months" },
      { value: "6-12", label: "6–12 months" },
      { value: "12-plus", label: "12+ months" },
    ],
  },
  {
    id: "portfolio_count",
    question: "How many companies are in your current portfolio?",
    type: "number",
    stage: "strategy",
    required: true,
    validation: { min: 0 },
  },
  {
    id: "geography",
    question: "What is your preferred geography?",
    type: "select",
    stage: "strategy",
    required: true,
    options: [
      { value: "north-america", label: "North America" },
      { value: "europe", label: "Europe" },
      { value: "asia", label: "Asia" },
      { value: "global", label: "Global" },
    ],
  },
  {
    id: "follow_on_strategy",
    question: "What is your follow-on investment strategy?",
    type: "textarea",
    stage: "strategy",
    required: true,
    validation: { minLength: 50 },
  },
  {
    id: "value_add",
    question: "How do you add value to your portfolio companies?",
    type: "textarea",
    stage: "strategy",
    required: true,
    validation: { minLength: 50 },
  },
  {
    id: "decision_timeline",
    question: "How quickly do you typically make investment decisions?",
    type: "select",
    stage: "timeline",
    required: true,
    options: [
      { value: "1-2", label: "1–2 weeks" },
      { value: "2-4", label: "2–4 weeks" },
      { value: "4-8", label: "4–8 weeks" },
      { value: "8-plus", label: "8+ weeks" },
    ],
  },
  {
    id: "actively_investing",
    question: "Are you actively investing right now?",
    type: "select",
    stage: "timeline",
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "not-yet", label: "Not yet" },
      { value: "paused", label: "Paused" },
    ],
  },
  {
    id: "looking_for_deals",
    question: "Are you currently looking for new deals?",
    type: "boolean",
    stage: "timeline",
    required: true,
  },
  {
    id: "investment_thesis",
    question: "Upload your investment thesis",
    type: "file",
    stage: "timeline",
    required: true,
    helperText: "PDF only, max 10MB. Drag & drop or click to browse.",
  },
];

export const investorFlow: QuestionFlow = {
  type: "investor",
  title: "Investor Qualification",
  description:
    "Help us understand your investment thesis so we can surface the best opportunities.",
  questions: investorQuestions,
  totalQuestions: investorQuestions.length,
  stages: ["personal", "profile", "strategy", "timeline"],
};
